### ISSUE TITLE
Download problems

### ISSUE THREAD

**Issue by samuelgarcia** [flatironinstitute/spikeforest_old#37]
Hi all,
I try to download locally with:

```python
recdir = 'sha1dir://fb52d510d2543634e247e0d2d1d4390be9ed9e20.synth_magland/datasets_noise10_K10_C4/001_synth'
recording = SFMdaRecordingExtractor(dataset_directory=recdir, download=True)
sorting_gt = SFMdaSortingExtractor(firings_file=recdir + '/firings_true.mda') 
```

but I have this 
```
Exception: Unable to find file: sha1dir://fb52d510d2543634e247e0d2d1d4390be9ed9e20.synth_magland/datasets_noise10_K10_C4/001_synth/params.json
```

Does the sha1 key sometimes ?

**Comment by samuelgarcia** [comment]
OUps I was missing this:
mt.configDownloadFrom('spikeforest.public')

**Comment by samuelgarcia** [comment]
sorry

**Comment by samuelgarcia** [comment]
I finally have some other donwload problems.
I am trying to make a loop to donwload a dataset.

```python
recdir = 'sha1dir://fb52d510d2543634e247e0d2d1d4390be9ed9e20.synth_magland/datasets_noise10_K10_C4/001_synth'
```
is OK

But 
```python
recdir = 'sha1dir://fb52d510d2543634e247e0d2d1d4390be9ed9e20.synth_magland/datasets_noise10_K10_C4/002_synth'
```
fails.


Any ideas ?


Error:
```
sha1dir://fb52d510d2543634e247e0d2d1d4390be9ed9e20.synth_maglang/datasets_noise10_K10_C4/002_synth
Traceback (most recent call last):
  File "download_from_SF.py", line 78, in <module>
    download_one_study(familly, study)
  File "download_from_SF.py", line 46, in download_one_study
    recording = SFMdaRecordingExtractor(dataset_directory=recdir, download=True)
  File "/home/samuel/.virtualenvs/py36/lib/python3.6/site-packages/spikeforest/extractors/sfmdaextractors/sfmdaextractors.py", line 38, in __init__
    raise Exception('Unable to realize file: ' + self._timeseries_path)
Exception: Unable to realize file: sha1dir://fb52d510d2543634e247e0d2d1d4390be9ed9e20.synth_maglang/datasets_noise10_K10_C4/002_synth/raw.mda
```

**Comment by magland** [comment]
Only some recordings are publicly available. See https://github.com/flatironinstitute/spikeforest/blob/master/docs/tutorials/spike_sorting_spikeforest_recording.md

**Comment by samuelgarcia** [comment]
OK.I see, I should read more that the first 5 lines of example before coding :)
I though it was totally open.
What is the reason of not opening the entire datset ?


For instance, for some dataset having one unique file is useless because there is only one GT.
For instance, **PAIRED_MEA64C_YGER/paired_mea64c/20160415_patch2**
In that case, we need several files to make stats..
Nevertheless they can be download directly at zenodo.

**Comment by magland** [comment]
Thanks Samuel. Yes if they are available on zenodo they are public anyway. As of now (recently changed), all of the paired_* recordings are public, with the exception of boyden recordings as I'm not sure of the status of the conditions for those recordings.

Regarding the other recordings (e.g., simulated datasets)... we are still thinking about public (training) vs holdout (validation) recordings. This is something that needs to be addressed more carefully.

**Comment by johnboyg** [comment]
https://www.inboxdollars.com/r/1896815546?ref_src=link
